[theme]
base = "dark"
primaryColor = "#FFFFFF"
backgroundColor = "#0A0A0A"
secondaryBackgroundColor = "#161616"
textColor = "#F2F2F2"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
